name: "Bug"
description: "👾 버그가 발생했습니다."
body:
  - type: textarea
    attributes:
      label: Describe
      description: |
        버그에 관해 설명을 적어주세요
  - type: textarea
    attributes:
      label: Additional
      description: |
        추가적으로 필요한 정보를 작성해주세요.